services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: devops-web-app:1.0

    container_name: devops-web-app

    ports:
      - "${APP_PORT}:80"

    restart: unless-stopped
