services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: devops-web-app:latest-local

    container_name: devops-web-app

    ports:
      - "${APP_PORT:-8080}:80"

    restart: unless-stopped
